### ISSUE TITLE
Forbidden node creation

### ISSUE THREAD

**Issue by diego-rapoport** [phaazon/mind.nvim#44]
Hi people! First time trying to use this plugin which seems to be very interesting to me.
What happens is that I get "forbidden node creation" after trying to create a new node on main tree. Any clues what it could be?
I'm also using a LunarVim configuration base.

**Comment by diego-rapoport** [comment]
Ok, so I did `set: ma` and it worked almost entirely. I can use "add_inside_end" for example but not "add_below". Can someone explain me the differences?

**Comment by phaazon** [comment]
@diego-rapoport `add_below` creates a node below the node under the cursor, in the same parent. You can’t create a node below the root because the root doesn’t have a parent. Trying a node inside the root, put your cursor on that node and try `add_below` again. :)

That works for moving nodes around too.

**Comment by diego-rapoport** [comment]
> @diego-rapoport `add_below` creates a node below the node under the cursor, in the same parent. You can’t create a node below the root because the root doesn’t have a parent. Trying a node inside the root, put your cursor on that node and try `add_below` again. :)
> 
> That works for moving nodes around too.

Thank you very much for the explanation!! Using a little bit more things got easier to understand.
